services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /redacted/path/sonarr/data:/config
      - /mnt/redacted/tvshows:/tvshows
      - /mnt/redacted/anime:/anime
      - /mnt/redacted/downloads:/downloads
    restart: unless-stopped
    network_mode: "container:gluetun"  # Share network namespace with Gluetun container
    labels:
      - "traefik.enable=true"

      # HTTP Router (Redirect to HTTPS)
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"

      # HTTPS Router (Secure Access)
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarr-secure.service=sonarr"

      # Define Service & Port
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
