services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /redacted/path/radarr/data:/config
      - /mnt/redacted/movies:/movies        # optional
      - /mnt/redacted/downloads:/downloads  # optional
    restart: unless-stopped
    network_mode: "container:gluetun"  # Share network namespace with Gluetun container
    labels:
      - "traefik.enable=true"

      # HTTP Router (Redirect to HTTPS)
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"

      # HTTPS Router (Secure Access)
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr-secure.service=radarr"

      # Define Service & Port
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
