services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    networks:
      docker_network:
        ipv4_address: 192.168.X.X  # Redacted Static Address
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /redacted/path/uptimekuma/data:/app/data  # Redacted host data path
    ports:
      - "3001:3001"  # Uptime Kuma web UI
    restart: unless-stopped

networks:
  docker_network:
    external: true
