services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /redacted/path/qbittorrent/config:/config
      - /mnt/redacted/downloads:/downloads       # optional
      - /mnt/redacted/incomplete:/incomplete     # optional
    restart: always
    network_mode: "container:gluetun"  # Share network namespace with Gluetun container
    labels:
      - "traefik.enable=true"

      # HTTP Router (Redirect to HTTPS)
      - "traefik.http.routers.qbittorrent.entrypoints=http"
      - "traefik.http.routers.qbittorrent.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qbittorrent.middlewares=qbittorrent-https-redirect"

      # HTTPS Router (Secure Access)
      - "traefik.http.routers.qbittorrent-secure.entrypoints=https"
      - "traefik.http.routers.qbittorrent-secure.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.routers.qbittorrent-secure.tls=true"
      - "traefik.http.routers.qbittorrent-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.qbittorrent-secure.service=qbittorrent"

      # Define Service & Port
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8081"
