services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /redacted/path/bazarr/config:/config
      - /mnt/redacted/movies:/movies
      - /mnt/redacted/tvshows:/tvshows
      - /mnt/redacted/anime:/anime
    restart: unless-stopped
    network_mode: "container:gluetun"
    labels:
      - "traefik.enable=true"

      # HTTP Router (Redirect to HTTPS)
      - "traefik.http.routers.bazarr.entrypoints=http"
      - "traefik.http.routers.bazarr.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.middlewares.bazarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bazarr.middlewares=bazarr-https-redirect"

      # HTTPS Router (Secure Access)
      - "traefik.http.routers.bazarr-secure.entrypoints=https"
      - "traefik.http.routers.bazarr-secure.rule=Host(`REDACTED_DOMAIN`)"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.routers.bazarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.bazarr-secure.service=bazarr"

      # Define Service & Port
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
