services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM=REDACTED_PLEX_CLAIM_TOKEN
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /redacted/path/plex/library:/config
      - /mnt/redacted/tvshows:/tvshows
      - /mnt/redacted/movies:/movies
      - /mnt/redacted/anime:/anime
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    restart: unless-stopped
